import { v4 as uuidv4 } from "uuid";
import Request from "./request";
import Header from "./header";

type HI_TYPES =
  | "OPConsultation"
  | "DiagnosticReport"
  | "Prescription"
  | "ImmunizationRecord"
  | "DischargeSummary"
  | "HealthDocumentRecord"
  | "WellnessRecord"
  | "Invoice";

export default class Link extends Header {
  constructor(_baseUrl: string, _accessToken: string) {
    super(_baseUrl, _accessToken);
  }

  /**
   * Adds care contexts to a patient's ABHA account using the v3 HIE-CM endpoint.
   *
   * This replaces the deprecated v0.5 `AddContext` method. It requires a
   * `linkToken` (obtained via `generateToken`) and sends patient care-context
   * data with `hiType` and `count` fields.
   *
   * Headers are built inline following the existing `generateToken` v3 pattern.
   *
   * @param config - Configuration object
   * @param config.healthId - Patient's health ID used to derive X-CM-ID header
   * @param config.hipId - HIP ID sent as X-HIP-ID header
   * @param config.linkToken - Link token obtained from HIE-CM token generation
   * @param config.abhaNumber - Patient's ABHA number
   * @param config.abhaAddress - Patient's ABHA address
   * @param config.patients - Array of patient care-context entries, each with:
   *   - referenceNumber - Patient reference (encounter ID) in HIP system
   *   - display - Display name for the patient
   *   - careContexts - Array of { referenceNumber, display }
   *   - hiType - Type of health information (HI_TYPES)
   *   - count - Number of care contexts
   * @param config.requestId - Optional UUID for REQUEST-ID header (auto-generated if omitted)
   * @param config.timestamp - Optional ISO timestamp for TIMESTAMP header (auto-generated if omitted)
   * @returns The parsed API response
   */
  addCareContext = async (config: {
    healthId: string;
    hipId: string;
    linkToken: string;
    abhaNumber: string;
    abhaAddress: string;
    patients: Array<{
      referenceNumber: string;
      display: string;
      careContexts: Array<{
        referenceNumber: string;
        display: string;
      }>;
      hiType: HI_TYPES;
      count: number;
    }>;
    requestId?: string;
    timestamp?: string;
  }) => {
    this.setXCmId(config.healthId);
    const headers = {
      "REQUEST-ID": config.requestId ?? uuidv4(),
      TIMESTAMP: config.timestamp ?? new Date().toISOString(),
      "X-HIP-ID": config.hipId,
      "X-LINK-TOKEN": config.linkToken,
      "X-CM-ID": this.xCmId,
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.accessToken}`,
    };
    const url = `${this.baseUrl}/api/hiecm/hip/v3/link/carecontext`;
    const normalizedAbhaNumber = String(config.abhaNumber).replace(/-/g, "");
    const body = {
      abhaNumber: normalizedAbhaNumber,
      abhaAddress: config.abhaAddress,
      patient: config.patients,
    };

    const response = await new Request().request({
      headers,
      method: "POST",
      requestBody: body,
      url,
    });

    const raw = response.body;

    // 202 Accepted — async processing, body is typically empty
    if (response.status === 202) {
      return { status: 202 };
    }

    if (typeof raw === "object") {
      return raw;
    }

    if (typeof raw === "string") {
      if (raw.length === 0) {
        throw new Error(
          `ABDM returned an empty body. ` +
          `status=${response.status} (${response.statusText || 'unknown'}), ` +
          `url=${url}`
        );
      }
      try {
        return JSON.parse(raw);
      } catch (err) {
        throw new Error(
          `addCareContext: ABDM returned non-JSON response. ` +
          `status=${response.status} (${response.statusText || 'unknown'}), ` +
          `url=${url}. Body: ${String(raw).slice(0, 500)}`
        );
      }
    }

    throw new Error("Unexpected response type");
  };

  /**
   * HMIS/LMIS response to the HIE-CM callback for user-initiated linking (v3).
   *
   * This is called by the HIP in response to the discovery callback (section 5.3.2).
   * The HIP validates the transactionId against a previous discovery, sends an
   * authentication request to the patient (e.g. OTP), and returns the link
   * reference number with authentication metadata. The patient subsequently passes
   * the token via `/link/care-context/confirm` against the `link.referenceNumber`.
   *
   * Uses the v3 HIE-CM endpoint per ABDM M2 Sandbox Documentation v2.8 (section 5.3.7):
   * `POST /user-initiated-linking/v3/link/care-context/on-init`
   *
   * Possible errors returned:
   * - Patient reference number is invalid
   * - Care context reference numbers are invalid
   *
   * @param config - Configuration object
   * @param config.healthId - Patient's ABHA address (e.g. "user@sbx") used to derive X-CM-ID
   * @param config.transactionId - Transaction ID from the discovery callback, used for correlation
   * @param config.referenceNumber - Link reference number generated by the HIP for this linking attempt
   * @param config.authenticationType - Authentication type: "DIRECT" or "MEDIATE"
   * @param config.communicationMedium - Medium for patient communication (e.g. "MOBILE")
   * @param config.communicationHint - Hint for the communication (e.g. "OTP")
   * @param config.communicationExpiry - ISO timestamp for communication expiry (defaults to 10 min from now)
   * @param config.requestId - Optional UUID for REQUEST-ID header (auto-generated if omitted)
   * @param config.timestamp - Optional ISO timestamp for TIMESTAMP header (auto-generated if omitted)
   * @param config.callbackRequestId - The `requestId` from the HIE-CM discovery callback, sent in `response.requestId`
   * @param config.error - Optional error object if the HIP cannot process the link request
   * @returns The request body that was sent (for logging/reference)
   */
  onInit = async (config: {
    healthId: string;
    transactionId: string;
    referenceNumber: string;
    authenticationType: "DIRECT" | "MEDIATE";
    communicationMedium: string;
    communicationHint: string;
    communicationExpiry?: string;
    requestId?: string;
    timestamp?: string;
    callbackRequestId: string;
    error?: {
      code: number;
      message: string;
    };
  }) => {
    this.setXCmId(config.healthId);
    const headers = {
      "REQUEST-ID": config.requestId ?? uuidv4(),
      TIMESTAMP: config.timestamp ?? new Date().toISOString(),
      "X-CM-ID": this.xCmId,
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.accessToken}`,
    };
    const url = `${this.baseUrl}/api/hiecm/user-initiated-linking/v3/link/care-context/on-init`;
    const body: any = {
      transactionId: config.transactionId,
      link: {
        referenceNumber: config.referenceNumber,
        authenticationType: config.authenticationType,
        meta: {
          communicationMedium: config.communicationMedium,
          communicationHint: config.communicationHint,
          communicationExpiry:
            config.communicationExpiry ??
            new Date(new Date().getTime() + 10 * 60000).toISOString(),
        },
      },
      response: {
        requestId: config.callbackRequestId,
      },
    };

    if (config.error) {
      body.error = config.error;
    }

    await new Request().request({
      headers,
      method: "POST",
      requestBody: body,
      url,
    });

    return body;
  };

  /**
   * HMIS/LMIS response on confirm — called by HIP after the patient confirms
   * the link via OTP/token (User Initiated Linking v3).
   *
   * This is the HIP's response to the HIE-CM callback at
   * `{callback_url}/api/v3hip/link/care-context/confirm` (section 5.3.10).
   * The HIP returns the confirmed care contexts that have been linked to the
   * patient's ABHA account.
   *
   * Uses the v3 endpoint per ABDM M2 Sandbox Documentation v2.8 (section 5.3.11):
   * `POST /api/hiecm/user-initiated-linking/v3/link/care-context/on-confirm`
   *
   * @param config - Configuration object
   * @param config.healthId - Patient's ABHA address (e.g. "user@sbx") used to derive X-CM-ID
   * @param config.patients - Array of patient care-context entries that were confirmed, each with:
   *   - referenceNumber - Patient reference in HIP system
   *   - display - Display name for the patient
   *   - careContexts - Array of { referenceNumber, display }
   *   - hiType - Type of health information (HI_TYPES)
   *   - count - Number of care contexts
   * @param config.callbackRequestId - The `requestId` from the HIE-CM confirm callback, sent in `response.requestId`
   * @param config.requestId - Optional UUID for REQUEST-ID header (auto-generated if omitted)
   * @param config.timestamp - Optional ISO timestamp for TIMESTAMP header (auto-generated if omitted)
   * @returns The request body that was sent (for logging/reference)
   */
  onConfirm = async (config: {
    healthId: string;
    patients: Array<{
      referenceNumber: string;
      display: string;
      careContexts: Array<{
        referenceNumber: string;
        display: string;
      }>;
      hiType: HI_TYPES;
      count: number;
    }>;
    callbackRequestId: string;
    requestId?: string;
    timestamp?: string;
  }) => {
    this.setXCmId(config.healthId);
    const headers = {
      "REQUEST-ID": config.requestId ?? uuidv4(),
      TIMESTAMP: config.timestamp ?? new Date().toISOString(),
      "X-CM-ID": this.xCmId,
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.accessToken}`,
    };
    const url = `${this.baseUrl}/api/hiecm/user-initiated-linking/v3/link/care-context/on-confirm`;
    const body = {
      patient: config.patients,
      response: {
        requestId: config.callbackRequestId,
      },
    };

    await new Request().request({
      headers,
      method: "POST",
      requestBody: body,
      url,
    });

    return body;
  };

  /**
   * Notifies the ABDM Consent Manager about new health data added/created for a patient
   * under an already-linked care context (HIP Initiated Linking v3).
   *
   * Called by HIP when new health information is added under a care context that
   * is already linked with the patient's ABHA account. This API should NOT be called
   * if the new health data is added under a new (unlinked) care context.
   *
   * Uses the v3 HIE-CM endpoint `/api/hiecmhip/v3/link/context/notify` per the
   * ABDM M2 Sandbox Documentation v2.8 (section 4.3.6).
   *
   * Headers are built inline following the v3 pattern used by `generateToken` and
   * `addCareContext`, including `X-HIP-ID`, `X-LINK-TOKEN`, `REQUEST-ID`, and
   * `TIMESTAMP` as required by the v3 API.
   *
   * @param config - Configuration object
   * @param config.healthId - Patient's identifier (ABHA address, e.g. "user@sbx") used to derive X-CM-ID
   * @param config.hipId - HIP facility ID sent as X-HIP-ID header (e.g. "IN2910000004")
   * @param config.linkToken - Link token (JWT) obtained from token generation, sent as X-LINK-TOKEN header
   * @param config.patientReference - Patient's reference number in the HIP system (e.g. ABHA number)
   * @param config.careContextReference - Care context reference under which new health data was added
   * @param config.hiTypes - Array of HI types for the new health data (e.g. ["Prescription", "DischargeSummary"])
   * @param config.date - ISO 8601 UTC date when the health information was created/added on the HIP
   * @param config.requestId - Optional UUID for REQUEST-ID header (auto-generated if omitted)
   * @param config.timestamp - Optional ISO timestamp for TIMESTAMP header (auto-generated if omitted)
   * @returns The request body that was sent (for logging/reference)
   */
  notify = async (config: {
    healthId: string;
    hipId: string;
    linkToken: string;
    patientReference: string;
    careContextReference: string;
    hiTypes: HI_TYPES[];
    date: string;
    requestId?: string;
    timestamp?: string;
  }) => {
    this.setXCmId(config.healthId);
    const headers = {
      "REQUEST-ID": config.requestId ?? uuidv4(),
      TIMESTAMP: config.timestamp ?? new Date().toISOString(),
      "X-HIP-ID": config.hipId,
      "X-LINK-TOKEN": config.linkToken,
      "X-CM-ID": this.xCmId,
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.accessToken}`,
    };
    const url = `${this.baseUrl}/api/hiecm/hip/v3/link/context/notify`;

    const body = {
      notification: {
        patient: {
          id: config.healthId,
        },
        careContext: {
          patientReference: config.patientReference,
          careContextReference: config.careContextReference,
        },
        hiTypes: config.hiTypes,
        date: config.date,
        hip: {
          id: config.hipId,
        },
      },
    };

    await new Request().request({
      headers,
      method: "POST",
      requestBody: body,
      url,
    });

    return body;
  };

  /**
   * Generates a patient token (ABDM HIE-CM v3 endpoint) required for HIE (Health Information Exchange) operations.
   *
   * This token is needed to authorize subsequent HIE transactions such as data push and data pull requests.
   * The API uses the v3 endpoint `/api/hiecm/v3/token/generate-token` which requires custom headers
   * (REQUEST-ID, TIMESTAMP, X-HIP-ID) not present in the standard v0.5 header set.
   *
   * @param config - Configuration object for token generation
   * @param config.healthId - Patient's health ID used to derive the X-CM-ID header (e.g., "user@abdm")
   * @param config.hipId - Health Information Provider ID sent as X-HIP-ID header
   * @param config.abhaNumber - Patient's ABHA number (can be numeric or string)
   * @param config.abhaAddress - Patient's ABHA address (e.g., "user@sbx")
   * @param config.name - Patient's full name
   * @param config.gender - Patient's gender
   * @param config.yearOfBirth - Patient's year of birth
   * @param config.requestId - Optional UUID for REQUEST-ID header (auto-generated if omitted)
   * @param config.timestamp - Optional ISO timestamp for TIMESTAMP header (auto-generated if omitted)
   * @returns The parsed API response containing the generated patient token
   */
  generateToken = async (config: {
    healthId: string;
    hipId: string;
    abhaNumber: number | string;
    abhaAddress: string;
    name: string;
    gender: string;
    yearOfBirth: number;
    requestId?: string;
    timestamp?: string;
  }) => {
    this.setXCmId(config.healthId);
    const headers = {
      "REQUEST-ID": config.requestId ?? uuidv4(),
      TIMESTAMP: config.timestamp ?? new Date().toISOString(),
      "X-HIP-ID": config.hipId,
      "X-CM-ID": this.xCmId,
      "Content-Type": "application/json",
      Authorization: `Bearer ${this.accessToken}`,
    };

    const normalizedAbhaNumber = String(config.abhaNumber).replace(/-/g, "");
    const url = `${this.baseUrl}/api/hiecm/v3/token/generate-token`;
    const body = {
      abhaNumber: normalizedAbhaNumber,
      abhaAddress: config.abhaAddress,
      name: config.name,
      gender: config.gender,
      yearOfBirth: config.yearOfBirth,
    };
    const response = await new Request().request({
      headers,
      method: "POST",
      requestBody: body,
      url,
    });

    const raw = response.body;

    console.log("ABDM RAW RESPONSE:", raw);

    // Case 1: 202 Accepted — async processing, body is typically empty
    if (response.status === 202) {
      return { status: 202 };
    }

    // Case 2: already an object
    if (typeof raw === "object") {
      return raw;
    }

    // Case 3: string → try parse
    if (typeof raw === "string") {
      if (raw.length === 0) {
        throw new Error(
          `ABDM returned an empty body. ` +
          `status=${response.status} (${response.statusText || 'unknown'}), ` +
          `url=${url}`
        );
      }
      try {
        return JSON.parse(raw);
      } catch (err) {
        throw new Error(
          `ABDM returned non-JSON response. ` +
          `status=${response.status} (${response.statusText || 'unknown'}), ` +
          `url=${url}. Body: ${String(raw).slice(0, 500)}`
        );
      }
    }

    // Fallback
    throw new Error("Unexpected response type");
  };
}
